### ISSUE TITLE
Bug Issue on Milestone 2 issue #17

### ISSUE THREAD

**Issue by B747400ERAF** [Estia-advanced-programming/pandora-public#104]
**Describe the bug**
Unrealistic temperature

**To Reproduce**
matthieu@MacBook-Pro pandora-2024-the_smooth_valleys % pandora -o maxTemp test/resources/common/0_301_Su-25T.frd
Maximum Temperature in the Cockpit: 69380955,12 ℃

**Expected behavior**
Plausible temp

**Code**

**Additional context**
No additional context

**Comment by dhmmasson** [comment]
I Have removed your code from the comment, the issue should be about the project not your solution. 
If you want me to look into your code, create a Pull Request in your own repository and @ me. 

you can look into the file the max temperature seems to be 33.64336311860708. If you read any other value the issue is in your code, not on the project.
